/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.cs4911.video_editor.testproto;

@SuppressWarnings("all")
public interface TestProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"TestProtocol\",\"namespace\":\"com.cs4911.video_editor.testproto\",\"types\":[],\"messages\":{\"addBlurEffect\":{\"request\":[],\"response\":\"null\"},\"addColorSaturationEffect\":{\"request\":[],\"response\":\"null\"},\"addDrawingEffect\":{\"request\":[],\"response\":\"null\"},\"addEdgeDetectionEffect\":{\"request\":[],\"response\":\"null\"},\"addGradientMagnitudeEffect\":{\"request\":[],\"response\":\"null\"},\"addGrayscaleEffect\":{\"request\":[],\"response\":\"null\"},\"addHorizontalFlipEffect\":{\"request\":[],\"response\":\"null\"},\"addHoughCircleEffect\":{\"request\":[],\"response\":\"null\"},\"addHoughLineEffect\":{\"request\":[],\"response\":\"null\"},\"addIdentityEffect\":{\"request\":[],\"response\":\"null\"},\"addMotionHistoryEffect\":{\"request\":[],\"response\":\"null\"},\"addNegativeEffect\":{\"request\":[],\"response\":\"null\"},\"addSeamCarveEffect\":{\"request\":[],\"response\":\"null\"},\"addSepiaEffect\":{\"request\":[],\"response\":\"null\"},\"addVerticalEffect\":{\"request\":[],\"response\":\"null\"},\"addXrayEffect\":{\"request\":[],\"response\":\"null\"},\"clearEffects\":{\"request\":[],\"response\":\"null\"},\"addFrames\":{\"request\":[{\"name\":\"frames\",\"type\":{\"type\":\"array\",\"items\":\"bytes\"}}],\"response\":{\"type\":\"array\",\"items\":\"bytes\"}}}}");
  java.lang.Void addBlurEffect() throws org.apache.avro.AvroRemoteException;
  java.lang.Void addColorSaturationEffect() throws org.apache.avro.AvroRemoteException;
  java.lang.Void addDrawingEffect() throws org.apache.avro.AvroRemoteException;
  java.lang.Void addEdgeDetectionEffect() throws org.apache.avro.AvroRemoteException;
  java.lang.Void addGradientMagnitudeEffect() throws org.apache.avro.AvroRemoteException;
  java.lang.Void addGrayscaleEffect() throws org.apache.avro.AvroRemoteException;
  java.lang.Void addHorizontalFlipEffect() throws org.apache.avro.AvroRemoteException;
  java.lang.Void addHoughCircleEffect() throws org.apache.avro.AvroRemoteException;
  java.lang.Void addHoughLineEffect() throws org.apache.avro.AvroRemoteException;
  java.lang.Void addIdentityEffect() throws org.apache.avro.AvroRemoteException;
  java.lang.Void addMotionHistoryEffect() throws org.apache.avro.AvroRemoteException;
  java.lang.Void addNegativeEffect() throws org.apache.avro.AvroRemoteException;
  java.lang.Void addSeamCarveEffect() throws org.apache.avro.AvroRemoteException;
  java.lang.Void addSepiaEffect() throws org.apache.avro.AvroRemoteException;
  java.lang.Void addVerticalEffect() throws org.apache.avro.AvroRemoteException;
  java.lang.Void addXrayEffect() throws org.apache.avro.AvroRemoteException;
  java.lang.Void clearEffects() throws org.apache.avro.AvroRemoteException;
  java.util.List<java.nio.ByteBuffer> addFrames(java.util.List<java.nio.ByteBuffer> frames) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends TestProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = com.cs4911.video_editor.testproto.TestProtocol.PROTOCOL;
    void addBlurEffect(org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void addColorSaturationEffect(org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void addDrawingEffect(org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void addEdgeDetectionEffect(org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void addGradientMagnitudeEffect(org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void addGrayscaleEffect(org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void addHorizontalFlipEffect(org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void addHoughCircleEffect(org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void addHoughLineEffect(org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void addIdentityEffect(org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void addMotionHistoryEffect(org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void addNegativeEffect(org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void addSeamCarveEffect(org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void addSepiaEffect(org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void addVerticalEffect(org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void addXrayEffect(org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void clearEffects(org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void addFrames(java.util.List<java.nio.ByteBuffer> frames, org.apache.avro.ipc.Callback<java.util.List<java.nio.ByteBuffer>> callback) throws java.io.IOException;
  }
}